### ISSUE TITLE
question1

### ISSUE THREAD

**Issue by ailinliang** [WangCH69/Two-layer-contract-net-algorithm#2]
How to set different subnet_task_capacity for different subnets?

**Comment by WangCH69** [comment]
In 'experiments.py' there is an option of 'subnet_task_capacity' and you can adjust it there.
Be aware that this setting is independent in each subnet.

**Comment by ailinliang** [comment]
'subnet_task_capacity':[{3},{3},{3}],
我这样写，但是好像没有作用，您能帮忙看看问题在哪么？
另外，您可以提供一个关于您的代码的解释的文档么？百忙之中打扰您，万分感谢

论文33
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WangCH69/Two-layer-contract-net-algorithm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月7日(星期三) 下午4:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WangCH69/Two-layer-contract-net-algorithm] question1 (Issue #2)





 
In 'experiments.py' there is an option of 'subnet_task_capacity' and you can adjust it there.
 Be aware that this setting is independent in each subnet.
